import type { ProofItem } from "@/lib/site-data";

/**
 * Реальные работы «до/после» трихопигментации (SMP) Алёны Алмасовой.
 * Фото оптимизированы в WebP и лежат в /public/images/works.
 * Поле `gender` управляет гендер-фильтром галереи (см. WorksGallery).
 * Ключевые слова в title/details подобраны так, чтобы concern-страницы
 * (getConcernGalleryItems) находили релевантные кейсы по «макуш/пересад/поред/густ».
 */
export const allWorks: ProofItem[] = [
  {
    title: "Пробор у женщины",
    details: "Поредение по пробору — вернули визуальную густоту волос без операций",
    sessions: "2–3 сеанса",
    imageSrc: "/images/works/probor-zhenshchina-1.webp",
    alt: "Трихопигментация пробора у женщины при поредении волос: до и после",
    gender: "female",
  },
  {
    title: "Женское поредение",
    details: "Просвечивающий пробор стал визуально гуще, кожа больше не видна",
    sessions: "2–3 сеанса",
    imageSrc: "/images/works/probor-zhenshchina-2.webp",
    alt: "Трихопигментация при женском поредении волос по пробору: до и после",
    gender: "female",
  },
  {
    title: "Линия роста волос",
    details: "Проработали переднюю линию роста и зону пробора у женщины",
    sessions: "2 сеанса",
    imageSrc: "/images/works/liniya-rosta-zhenshchina-1.webp",
    alt: "Трихопигментация линии роста волос у женщины: до и после",
    gender: "female",
  },
  {
    title: "Облысение без пересадки",
    details:
      "Плотный эффект бритой головы вместо дорогой пересадки — залысины больше не видны",
    sessions: "2–3 сеанса",
    imageSrc: "/images/works/lysina-muzhchina-bez-peresadki.webp",
    alt: "Трихопигментация при мужском облысении как альтернатива пересадке волос: до и после",
    gender: "male",
  },
  {
    title: "Макушка",
    details: "Просвечивающую макушку у мужчины сделали визуально плотной",
    sessions: "2–3 сеанса",
    imageSrc: "/images/works/makushka-muzhchina-1.webp",
    alt: "Трихопигментация макушки у мужчины: до и после",
    gender: "male",
  },
  {
    title: "Загущение волос",
    details: "Натуральный эффект густоты на коротких волосах у мужчины",
    sessions: "2 сеанса",
    imageSrc: "/images/works/zagushchenie-muzhchina-1.webp",
    alt: "Трихопигментация для загущения волос у мужчины: до и после",
    gender: "male",
  },
  {
    title: "Затылок",
    details: "Выровняли густоту на затылочной зоне, поредение стало незаметным",
    sessions: "2 сеанса",
    imageSrc: "/images/works/zatylok-muzhchina-1.webp",
    alt: "Трихопигментация затылка у мужчины: до и после",
    gender: "male",
  },
  {
    title: "Линия роста",
    details: "Натуральная плотность передней линии роста волос после 2 сеанса",
    sessions: "2 сеанса",
    imageSrc: "/images/works/liniya-rosta-muzhchina-1.webp",
    alt: "Трихопигментация линии роста волос у мужчины: до и после",
    gender: "male",
  },
  {
    title: "Передняя зона",
    details: "Восстановили чёткую линию роста волос и убрали залысины",
    sessions: "2–3 сеанса",
    imageSrc: "/images/works/liniya-rosta-muzhchina-2.webp",
    alt: "Трихопигментация передней линии роста волос: до и после",
    gender: "male",
  },
  {
    title: "Затылок и виски",
    details: "Ровная густота по затылку и вискам после залысин",
    sessions: "2 сеанса",
    imageSrc: "/images/works/zatylok-muzhchina-2.webp",
    alt: "Трихопигментация затылка и висков у мужчины: до и после",
    gender: "male",
  },
  {
    title: "Виски",
    details: "Убрали залысины на висках, линия стала плотной",
    sessions: "2 сеанса",
    imageSrc: "/images/works/viski-muzhchina-1.webp",
    alt: "Трихопигментация висков у мужчины при залысинах: до и после",
    gender: "male",
  },
  {
    title: "Макушка сверху",
    details: "Вид сверху: макушка перестала просвечивать, густота восстановлена",
    sessions: "2–3 сеанса",
    imageSrc: "/images/works/makushka-muzhchina-2.webp",
    alt: "Трихопигментация макушки, вид сверху: до и после",
    gender: "male",
  },
  {
    title: "Редеющая макушка",
    details: "Загустили редеющую макушку, поредение стало незаметным",
    sessions: "2–3 сеанса",
    imageSrc: "/images/works/makushka-muzhchina-3.webp",
    alt: "Трихопигментация редеющей макушки у мужчины: до и после",
    gender: "male",
  },
  {
    title: "Густота без операций",
    details: "Эффект густоты по пробору у женщины без пересадки волос",
    sessions: "2–3 сеанса",
    imageSrc: "/images/works/probor-zhenshchina-3.webp",
    alt: "Трихопигментация для густоты волос у женщины без операций: до и после",
    gender: "female",
  },
  {
    title: "В процессе работы",
    details: "Фото пробора в процессе процедуры трихопигментации",
    sessions: "по этапам",
    imageSrc: "/images/works/probor-process.webp",
    alt: "Трихопигментация пробора в процессе процедуры",
    gender: "female",
  },
  {
    title: "Виски у женщины",
    details: "Виски снова выглядят густыми — результат после 1 и 3 сеанса",
    sessions: "1–3 сеанса",
    imageSrc: "/images/works/viski-zhenshchina-1.webp",
    alt: "Трихопигментация висков у женщины: до и после",
    gender: "female",
  },
  {
    title: "Затылочная зона",
    details: "Скрыли поредение на затылке, густота выровнена",
    sessions: "индивидуально",
    imageSrc: "/images/works/zatylok-1.webp",
    alt: "Трихопигментация затылочной зоны: до и после",
    gender: "male",
  },
  {
    title: "После пересадки",
    details: "Маскировка просветов между графтами после пересадки волос",
    sessions: "индивидуально",
    imageSrc: "/images/works/posle-peresadki-1.webp",
    alt: "Трихопигментация после пересадки волос, маскировка просветов: до и после",
    gender: "male",
  },
  {
    title: "Плотность после пересадки",
    details: "Догустили зоны, где пересадка дала мало плотности",
    sessions: "индивидуально",
    imageSrc: "/images/works/posle-peresadki-2.webp",
    alt: "Трихопигментация после пересадки волос для плотности: до и после",
    gender: "male",
  },
  {
    title: "Коррекция после пересадки",
    details: "Добавили густоты после пересадки — момент за 3 сеанса",
    sessions: "3 сеанса",
    imageSrc: "/images/works/posle-peresadki-3.webp",
    alt: "Коррекция плотности после пересадки волос: до и после",
    gender: "male",
  },
  {
    title: "Натуральное загущение",
    details: "Максимально натуральное загущение по пробору — результат после 3 сеансов",
    sessions: "3 сеанса",
    imageSrc: "/images/works/zagushchenie-probor-1.webp",
    alt: "Натуральное загущение волос трихопигментацией по пробору: до и после",
    gender: "female",
  },
  {
    title: "Отзыв клиента",
    details: "Кожа головы больше не просвечивает на макушке — с отзывом клиента",
    sessions: "2–3 сеанса",
    imageSrc: "/images/works/makushka-otzyv.webp",
    alt: "Трихопигментация макушки с отзывом клиента: до и после",
    gender: "male",
  },
  {
    title: "Тёмный пробор",
    details: "Кожа не просвечивает по пробору — результат после 3 сеанса",
    sessions: "3 сеанса",
    imageSrc: "/images/works/probor-zhenshchina-4.webp",
    alt: "Трихопигментация пробора на тёмных волосах у женщины: до и после",
    gender: "female",
  },
  {
    title: "Лысина в стиль",
    details: "Полностью бритая голова превращается в стильный образ с эффектом густоты",
    sessions: "2–3 сеанса",
    imageSrc: "/images/works/lysina-muzhchina-stil.webp",
    alt: "Трихопигментация бритой головы у мужчины: до и после",
    gender: "male",
  },
  {
    title: "Имитация густоты",
    details: "Имитация густоты волос на макушке — фото на следующий день",
    sessions: "2 сеанса",
    imageSrc: "/images/works/imitaciya-gustoty-muzhchina.webp",
    alt: "Трихопигментация для имитации густоты волос у мужчины: до и после",
    gender: "male",
  },
  {
    title: "Пробор крупно",
    details: "Кожа головы по пробору больше не просвечивает, густота восстановлена",
    sessions: "2–3 сеанса",
    imageSrc: "/images/works/probor-zhenshchina-5.webp",
    alt: "Трихопигментация пробора крупным планом у женщины: до и после",
    gender: "female",
  },
];

/** Кейсы для мужского варианта (+ универсальные). */
export const worksMale = allWorks.filter((w) => w.gender !== "female");
/** Кейсы для женского варианта (+ универсальные). */
export const worksFemale = allWorks.filter((w) => w.gender !== "male");
